add gitlab installer

diff --git a/install/source/gitlab-installer-script.yaml b/install/source/gitlab-installer-script.yaml
--- a/install/source/gitlab-installer-script.yaml
+++ b/install/source/gitlab-installer-script.yaml
@@ -20,12 +20,12 @@ data:
         configureCertmanager: false
       hosts:
         domain: gitlab.svc
-        https: false
+        https: true
         gitlab:
-          https: false
+          https: true
         registry:
           servicePort: 5000
-          https: false
+          https: true
         minio:
           https: false
     nginx-ingress:
@@ -70,6 +70,8 @@ data:
 
     GITLAB_NAMESPACE="gitlab"
     GITLAB_CONFIG_SETTING_RETRY=60
+    GIT_API_BASE="http://gitlab-webservice-default:8181"
+
 
     BASEDIR=$(dirname $0)
 
@@ -155,7 +157,7 @@ data:
     #
     echo "[INFO] START : Generate root token"
     TOKEN_LENGTH=20
-    ROOT_TOKEN=$(cat /dev/urandom | base64 | fold -w 20 | head -n 1)
+    ROOT_TOKEN=$(cat /dev/urandom | sed -e 's/[^A-Za-z0-9]//g' | base64 | fold -w 20 | head -n 1)
     if [ $? -ne 0 ]; then
       echo "[ERROR] generate ROOT_TOKEN"
     fi
@@ -186,8 +188,6 @@ data:
     #
     # configure gitlab
     #
-    GIT_API_BASE="http://gitlab-webservice-default:8181"
-
     EXITCODE_PUT_enabled_git_access_protocol=-1
     EXITCODE_allow_local_requests_from_web_hooks_and_services=-1
     EXITCODE_allow_local_requests_from_hooks_and_services=-1
@@ -197,13 +197,16 @@ data:
 
         if [ ${EXITCODE_PUT_enabled_git_access_protocol} -ne 0 ]; then
           echo -n "[INFO] Setting enabled_git_access_protocol : "
-          curl -X PUT \
+          STATUS_CODE=$( \
+            curl -X PUT \
             -H 'Content-Type: application/json' \
             -H "PRIVATE-TOKEN: ${ROOT_TOKEN}" \
-            "${GIT_API_BASE}/api/v4/application/settings?enabled_git_access_protocol=http" &> /dev/null
+            -w '%{http_code}\n' -o /dev/null \
+            "${GIT_API_BASE}/api/v4/application/settings?enabled_git_access_protocol=http" \
+          )
 
-          EXITCODE_PUT_enabled_git_access_protocol=$?
-          if [ ${EXITCODE_PUT_enabled_git_access_protocol} -eq 0 ]; then
+          if [ $? -eq 0 -a "${STATUS_CODE}" = "200" ]; then
+            EXITCODE_PUT_enabled_git_access_protocol=0
             echo "DONE"
           else
             echo "FAIL"
@@ -213,13 +216,16 @@ data:
 
         if [ ${EXITCODE_allow_local_requests_from_web_hooks_and_services} -ne 0 ]; then
           echo -n "[INFO] Setting allow_local_requests_from_web_hooks_and_services : "
-          curl -X PUT \
-            -H 'Content-Type: application/json' \
-            -H "PRIVATE-TOKEN: ${ROOT_TOKEN}" \
-            "${GIT_API_BASE}/api/v4/application/settings?allow_local_requests_from_web_hooks_and_services=true" &> /dev/null
+          STATUS_CODE=$( \
+            curl -X PUT \
+              -H 'Content-Type: application/json' \
+              -H "PRIVATE-TOKEN: ${ROOT_TOKEN}" \
+              -w '%{http_code}\n' -o /dev/null \
+              "${GIT_API_BASE}/api/v4/application/settings?allow_local_requests_from_web_hooks_and_services=true" \
+          )
 
-          EXITCODE_allow_local_requests_from_web_hooks_and_services=$?
-          if [ ${EXITCODE_allow_local_requests_from_web_hooks_and_services} -eq 0 ]; then
+          if [ $? -eq 0 -a "${STATUS_CODE}" = "200" ]; then
+            EXITCODE_allow_local_requests_from_web_hooks_and_services=0
             echo "DONE"
           else
             echo "FAIL"
@@ -227,20 +233,24 @@ data:
           fi
         fi
 
-        if [ ${EXITCODE_allow_local_requests_from_hooks_and_services} -ne 0 ]; then
-          echo -n "[INFO] Setting allow_local_requests_from_hooks_and_services : "
-          curl -X PUT \
-            -H 'Content-Type: application/json' \
-            -H "PRIVATE-TOKEN: ${ROOT_TOKEN}" \
-            "${GIT_API_BASE}/api/v4/application/settings?allow_local_requests_from_hooks_and_services=true" &> /dev/null
-          EXITCODE_allow_local_requests_from_hooks_and_services=$?
-          if [ ${EXITCODE_allow_local_requests_from_hooks_and_services} -eq 0 ]; then
-            echo "DONE"
-          else
-            echo "FAIL"
-            continue
-          fi
-        fi
+        EXITCODE_allow_local_requests_from_hooks_and_services=0
+        # if [ ${EXITCODE_allow_local_requests_from_hooks_and_services} -ne 0 ]; then
+        #   echo -n "[INFO] Setting allow_local_requests_from_hooks_and_services : "
+        #   STATUS_CODE=$( \
+        #     curl -X PUT \
+        #       -H 'Content-Type: application/json' \
+        #       -H "PRIVATE-TOKEN: ${ROOT_TOKEN}" \
+        #       "${GIT_API_BASE}/api/v4/application/settings?allow_local_requests_from_hooks_and_services=true" \
+        #   )
+
+        #   if [ $? -eq 0 -a "${STATUS_CODE}" = "200" ]; then
+        #     EXITCODE_allow_local_requests_from_hooks_and_services=0
+        #     echo "DONE"
+        #   else
+        #     echo "FAIL"
+        #     continue
+        #   fi
+        # fi
 
         break;
     done
