update setting-tools log

diff --git a/epochSetting/command/set-host b/epochSetting/command/set-host
--- a/epochSetting/command/set-host
+++ b/epochSetting/command/set-host
@@ -25,8 +25,8 @@ cat <<EOF
 EOF
 
 if [ $# -ne 1 ]; then
-    echo "Usage : `basename $0` [hostname or IPaddress]"
-    echo "ERROR : Check the parameters and try again"
+    echo "[ERROR] Usage : `basename $0` [hostname or IPaddress]"
+    echo "[ERROR] Check the parameters and try again"
     exit 1
 fi
 
@@ -41,6 +41,10 @@ done
 
 echo "[INFO] Call set-host command"
 kubectl exec -i deploy/epoch-setting-tools -n epoch-system -- bash /scripts/set-host.sh $1
+if [ $? -ne 0 ]; then
+  echo "[ERROR] Call set-host command"
+  exit 1
+fi
 
 echo "[INFO] Call set-host-gitlab command"
 cat <<EOF | sed -e "s/#HOST#/$1/g" | kubectl apply -f -
@@ -66,7 +70,10 @@ spec:
             kubectl exec -i deploy/epoch-setting-tools -n epoch-system -- bash /scripts/set-host-gitlab.sh #HOST# &&
             kubectl delete job/set-host-gitlab -n epoch-system
 EOF
+if [ $? -ne 0 ]; then
+  echo "[ERROR] Call set-host-gitlab command"
+  exit 1
+fi
 
-
-echo "**** ${BASENAME} completed successfully ****"
+echo "**** `basename $0` completed successfully ****"
 exit 0
diff --git a/install/epoch-install.yaml b/install/epoch-install.yaml
--- a/install/epoch-install.yaml
+++ b/install/epoch-install.yaml
@@ -7174,8 +7174,24 @@ data:
     #   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     #   See the License for the specific language governing permissions and
     #   limitations under the License.
+    BASENAME=$(basename "$0")
+    LOGFILE="/var/log/epoch/${BASENAME}.`date '+%Y%m%d'`"
+    CMD_RESULT="/tmp/result.$$"
+    LF='
+    '
 
-    echo "[INFO] START : set-host-gitlab.sh"
+    function logger() {
+        LOG_LEVEL=$1
+        LOG_MESSAGE=$2
+        LOG_TEXT="[`TZ=JST-9 date '+%Y/%m/%d %H:%M:%S'`][${BASENAME}][${LOG_LEVEL}] ${LOG_MESSAGE}"
+        if [ "${LOG_LEVEL}" != "DEBUG" ]; then
+            echo "[${LOG_LEVEL}] ${LOG_MESSAGE}"
+        fi
+        echo "${LOG_TEXT}" > /proc/1/fd/1
+        echo "${LOG_TEXT}" >> "${LOGFILE}"
+    }
+
+    logger "INFO" "START : set-host-gitlab.sh"
 
     GITLAB_NAMESPACE="gitlab"
     GITLAB_INSTALL_CHECK_TIMES=360
@@ -7185,15 +7201,16 @@ data:
     # check parameter
     #
     if [ $# -ne 1 ]; then
-        echo "Usage : ${BASENAME} [hostname or IPaddress]"
-        echo "ERROR : Check the parameters and try again"
+        logger "ERROR" "Usage : ${BASENAME} [hostname or IPaddress]"
+        logger "ERROR" "Check the parameters and try again"
         exit 1
     fi
 
     PRM_MY_HOST="$1"
     GITLAB_CLONE_URL="https://${PRM_MY_HOST}:31183/"
 
-    echo "[INFO] START : Wait Gitlab Installer finished"
+    logger "INFO" "START : Wait Gitlab Installer finished"
+
     INSTALLER_STATUS=""
     for ((i=1; i<=${GITLAB_INSTALL_CHECK_TIMES}; i++)); do
         sleep 10;
@@ -7205,30 +7222,30 @@ data:
             break;
         fi
         if [ "${INSTALLER_STATUS}" = "Error" ]; then
-            echo "[ERROR] CANCELED : because the installation failed"
+            logger "ERROR" "CANCELED : because the installation failed"
             exit 1
         fi
     done
     if [ "${INSTALLER_STATUS}" != "Complete" ]; then
-        echo "[ERROR] CANCELED : because the installation wait timeout"
+        logger "ERROR" "CANCELED : because the installation wait timeout"
         exit 1
     fi
 
-    echo "[INFO] START : Get TOKEN"
+    logger "INFO" "START : Get TOKEN"
     TOKEN=$(kubectl get secret gitlab-root-token -n ${GITLAB_NAMESPACE} -o jsonpath='{.data.TOKEN}' | base64 --decode)
     if [ $? -ne 0 ]; then
-        echo "[ERROR] CANCELED : Failed to get token"
+        logger "ERROR" "CANCELED : Failed to get token"
         exit 1
     fi
 
-    echo "[INFO] START : Encode CLONE URL"
+    logger "INFO" "START : Encode CLONE URL"
     GITLAB_CLONE_URL_ENC=$(echo "${GITLAB_CLONE_URL}" | perl -nle 's/([^\w ])/"%".unpack("H2",$1)/eg; s/ /\+/g; print')
     if [ $? -ne 0 ]; then
-        echo "[ERROR] encode clone url"
+        logger "ERROR" "encode clone url"
         exit 1
     fi
 
-    echo "[INFO] START : Setting custom_http_clone_url_root "
+    logger "INFO" "START : Setting custom_http_clone_url_root"
     SUCCEED_SETTING=0
 
     STATUS_CODE=$(
@@ -7238,14 +7255,14 @@ data:
         -w '%{http_code}\n' -o /dev/null \
         "${GIT_API_BASE}/api/v4/application/settings?custom_http_clone_url_root=${GITLAB_CLONE_URL_ENC}" \
     )
-    echo "[INFO] Setting custom_http_clone_url_root STATUS_CODE:${STATUS_CODE}"
+    logger "INFO" "Setting custom_http_clone_url_root STATUS_CODE:${STATUS_CODE}"
 
     if [ $? -ne 0 -o "${STATUS_CODE}" != "200" ]; then
-        echo "[FAIL] configuration was failed"
+        logger "ERROR" "configuration was failed"
         exit 1
     fi
 
-    echo "[INFO] configuration was successful"
+    logger "INFO" "configuration was successful"
     exit 0
   set-host.sh: |
     #!/bin/bash
@@ -7264,12 +7281,27 @@ data:
     #   limitations under the License.
 
 
-    echo "[INFO] START : set-host.sh"
+    BASENAME=$(basename "$0")
+    LOGFILE="/var/log/epoch/${BASENAME}.`date '+%Y%m%d'`"
+    CMD_RESULT="/tmp/result.$$"
+    LF='
+    '
+    function logger() {
+        LOG_LEVEL=$1
+        LOG_MESSAGE=$2
+        LOG_TEXT="[`TZ=JST-9 date '+%Y/%m/%d %H:%M:%S'`][${BASENAME}][${LOG_LEVEL}] ${LOG_MESSAGE}"
+        if [ "${LOG_LEVEL}" != "DEBUG" ]; then
+            echo "[${LOG_LEVEL}] ${LOG_MESSAGE}"
+        fi
+        echo "${LOG_TEXT}" > /proc/1/fd/1
+        echo "${LOG_TEXT}" >> "${LOGFILE}"
+    }
+
+    logger "INFO" "START : set-host.sh"
 
     #
     # Initialize variables
     #
-    BASENAME=$(basename "$0")
     STEP=0
     ALLSTEPS=5
 
@@ -7277,8 +7309,8 @@ data:
     # check parameter
     #
     if [ $# -ne 1 ]; then
-        echo "Usage : ${BASENAME} [hostname or IPaddress]"
-        echo "ERROR : Check the parameters and try again"
+        logger "ERROR" "Usage : ${BASENAME} [hostname or IPaddress]"
+        logger "ERROR" "Check the parameters and try again"
         exit 1
     fi
 
@@ -7288,41 +7320,41 @@ data:
     # Initialize Setting Parameter
     #
     STEP=$(expr ${STEP} + 1)
-    echo "**** STEP : ${STEP} / ${ALLSTEPS} : Initialize Setting Parameter ..."
+    logger "INFO" "**** STEP : ${STEP} / ${ALLSTEPS} : Initialize Setting Parameter ..."
 
     OIDC_PASSPHRASE=$(< /dev/urandom tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1 | sort | uniq)
     if [ $? -ne 0 -o -z "${OIDC_PASSPHRASE}" ]; then
-        echo "ERROR : Generate OIDC_PASSPHRASE"
+        logger "ERROR" "Generate OIDC_PASSPHRASE"
         exit 2
     fi
 
     OIDC_PASSPHRASE_B64=$(echo -n "${OIDC_PASSPHRASE}" | base64)
     if [ $? -ne 0 -o -z "${OIDC_PASSPHRASE_B64}" ]; then
-        echo "ERROR : Generate OIDC_PASSPHRASE_B64"
+        logger "ERROR" "Generate OIDC_PASSPHRASE_B64"
         exit 2
     fi
 
     KEYCLOAK_ADMIN_PASSW=$(< /dev/urandom tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1 | sort | uniq)
     if [ $? -ne 0 -o -z "${KEYCLOAK_ADMIN_PASSW}" ]; then
-        echo "ERROR : Generate KEYCLOAK_ADMIN_PASSW"
+        logger "ERROR" "Generate KEYCLOAK_ADMIN_PASSW"
         exit 2
     fi
 
     KEYCLOAK_ADMIN_PASSW_B64=$(echo -n "${KEYCLOAK_ADMIN_PASSW}" | base64)
     if [ $? -ne 0 -o -z "${KEYCLOAK_ADMIN_PASSW_B64}" ]; then
-        echo "ERROR : Generate OIDC_PASSPHRASE_B64"
+        logger "ERROR" "Generate KEYCLOAK_ADMIN_PASSW_B64"
         exit 2
     fi
 
     EPOCH_ADMIN_PASSWD=$(< /dev/urandom tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1 | sort | uniq)
-    if [ $? -ne 0 -o -z "${KEYCLOAK_ADMIN_PASSW}" ]; then
-        echo "ERROR : Generate EPOCH_ADMIN_PASSWD"
+    if [ $? -ne 0 -o -z "${EPOCH_ADMIN_PASSWD}" ]; then
+        logger "ERROR" "Generate EPOCH_ADMIN_PASSWD"
         exit 2
     fi
 
     EPOCH_ADMIN_PASSWD_B64=$(echo -n "${EPOCH_ADMIN_PASSWD}" | base64)
     if [ $? -ne 0 -o -z "${EPOCH_ADMIN_PASSWD_B64}" ]; then
-        echo "ERROR : Generate EPOCH_ADMIN_PASSWD_B64"
+        logger "ERROR" "Generate EPOCH_ADMIN_PASSWD_B64"
         exit 2
     fi
 
@@ -7330,29 +7362,34 @@ data:
     # Set parameter to configmap
     #
     STEP=$(expr ${STEP} + 1)
-    echo "**** STEP : ${STEP} / ${ALLSTEPS} : Set Parameter To Configmap"
+    logger "INFO" "**** STEP : ${STEP} / ${ALLSTEPS} : Set Parameter To Configmap"
 
     kubectl patch configmap -n epoch-system host-setting-config -p "\
     {\
         \"data\" : {\
             \"EPOCH_HOSTNAME\" : \"${PRM_MY_HOST}\"\
         }\
-    }"
+    }" &> "${CMD_RESULT}"
     if [ $? -ne 0 ]; then
-        echo "ERROR : patch configmap host-setting-config"
+        logger "ERROR" "CALL : kubectl patch configmap -n epoch-system host-setting-config${LF}`cat ${CMD_RESULT}`"
+        logger "ERROR" "patch configmap host-setting-config"
         exit 2
     fi
+    logger "INFO" "CALL : kubectl patch configmap -n epoch-system host-setting-config${LF}`cat ${CMD_RESULT}`"
+
 
     kubectl patch configmap -n exastro-platform-authentication-infra exastro-platform-authentication-infra-env -p "\
     {\
         \"data\" : {\
             \"EXASTRO_KEYCLOAK_HOST\" : \"${PRM_MY_HOST}\"\
         }\
-    }"
+    }" &> "${CMD_RESULT}"
     if [ $? -ne 0 ]; then
-        echo "ERROR : patch configmap exastro-platform-authentication-infra-env"
+        logger "ERROR" "CALL : kubectl patch configmap -n exastro-platform-authentication-infra exastro-platform-authentication-infra-env${LF}`cat ${CMD_RESULT}`"
+        logger "ERROR" "patch configmap exastro-platform-authentication-infra-env"
         exit 2
     fi
+    logger "INFO" "CALL : kubectl patch configmap -n exastro-platform-authentication-infra exastro-platform-authentication-infra-env${LF}`cat ${CMD_RESULT}`"
 
 
     kubectl patch configmap -n epoch-system epoch-service-api-config -p "\
@@ -7360,11 +7397,13 @@ data:
         \"data\" : {\
             \"EPOCH_EPAI_HOST\" : \"${PRM_MY_HOST}\"\
         }\
-    }"
+    }" &> "${CMD_RESULT}"
     if [ $? -ne 0 ]; then
-        echo "ERROR : patch configmap epoch-service-api-config"
+        logger "ERROR" "CALL : kubectl patch configmap -n epoch-system epoch-service-api-config${LF}`cat ${CMD_RESULT}`"
+        logger "ERROR" "patch configmap epoch-service-api-config"
         exit 2
     fi
+    logger "INFO" "CALL : kubectl patch configmap -n epoch-system epoch-service-api-config${LF}`cat ${CMD_RESULT}`"
 
 
     kubectl patch secret -n exastro-platform-authentication-infra exastro-platform-authentication-infra-secret -p "\
@@ -7374,67 +7413,74 @@ data:
             \"KEYCLOAK_PASSWORD\" : \"${KEYCLOAK_ADMIN_PASSW_B64}\",\
             \"EPOCH_PASSWORD\" : \"${EPOCH_ADMIN_PASSWD_B64}\"\
         }\
-    }"
+    }" &> "${CMD_RESULT}"
     if [ $? -ne 0 ]; then
-        echo "ERROR : patch secret exastro-platform-authentication-infra-secret"
+        logger "ERROR" "CALL : kubectl patch secret -n exastro-platform-authentication-infra exastro-platform-authentication-infra-secret${LF}`cat ${CMD_RESULT}`"
+        logger "ERROR" "patch secret exastro-platform-authentication-infra-secret"
         exit 2
     fi
+    logger "INFO" "CALL : kubectl patch secret -n exastro-platform-authentication-infra exastro-platform-authentication-infra-secret${LF}`cat ${CMD_RESULT}`"
 
     #
     # restart to reflect the settings
     #
     STEP=$(expr ${STEP} + 1)
-    echo "**** STEP : ${STEP} / ${ALLSTEPS} : restart to reflect the settings ..."
+    logger "INFO" "**** STEP : ${STEP} / ${ALLSTEPS} : restart to reflect the settings ..."
 
-    # kubectl rollout restart deploy -n epoch-system epoch-service-api
-    # if [ $? -ne 0 ]; then
-    #     echo "ERROR : rollout restart epoch-service-api"
-    #     exit 2
-    # fi
-
-    kubectl rollout restart deploy -n epoch-system epoch-service-api2
+    kubectl rollout restart deploy -n epoch-system epoch-service-api2 &> "${CMD_RESULT}"
     if [ $? -ne 0 ]; then
-        echo "ERROR : rollout restart epoch-service-api2"
+        logger "ERROR" "CALL : kubectl rollout restart deploy -n epoch-system epoch-service-api2${LF}`cat ${CMD_RESULT}`"
+        logger "ERROR" "rollout restart epoch-service-api2"
         exit 2
     fi
+    logger "INFO" "CALL : kubectl rollout restart deploy -n epoch-system epoch-service-api2${LF}`cat ${CMD_RESULT}`"
 
-    kubectl rollout restart deploy -n epoch-system epoch-control-ita-api
+    kubectl rollout restart deploy -n epoch-system epoch-control-ita-api &> "${CMD_RESULT}"
     if [ $? -ne 0 ]; then
-        echo "ERROR : rollout restart epoch-control-ita-api"
+        logger "ERROR" "CALL : kubectl rollout restart deploy -n epoch-system epoch-control-ita-api${LF}`cat ${CMD_RESULT}`"
+        logger "ERROR" "rollout restart epoch-control-ita-api"
         exit 2
     fi
+    logger "INFO" "CALL : kubectl rollout restart deploy -n epoch-system epoch-control-ita-api${LF}`cat ${CMD_RESULT}`"
 
     while true; do
         sleep 5;
         RESTART_BERFORE_API_POD=$(kubectl get pod --selector "name=authentication-infra-api" -n exastro-platform-authentication-infra -o jsonpath="{range .items[*]}{@.metadata.name}{\"\n\"}{end}" 2> /dev/null)
         if [ $? -eq 0 ]; then
+            logger "DEBUG" "RESTART_BERFORE_API_POD=${RESTART_BERFORE_API_POD}"
             break;
         fi
     done
-    kubectl rollout restart deploy -n exastro-platform-authentication-infra authentication-infra-api
+
+    kubectl rollout restart deploy -n exastro-platform-authentication-infra authentication-infra-api &> "${CMD_RESULT}"
     if [ $? -ne 0 ]; then
-        echo "ERROR : rollout restart authentication-infra-api"
+        logger "ERROR" "CALL : kubectl rollout restart deploy -n exastro-platform-authentication-infra authentication-infra-api${LF}`cat ${CMD_RESULT}`"
+        logger "ERROR" "rollout restart authentication-infra-api"
         exit 2
     fi
+    logger "INFO" "CALL : kubectl rollout restart deploy -n exastro-platform-authentication-infra authentication-infra-api${LF}`cat ${CMD_RESULT}`"
 
     while true; do
         sleep 5;
         RESTART_BERFORE_KEYCLOAK_POD=$(kubectl get pod --selector "app=keycloak" -n exastro-platform-authentication-infra -o jsonpath="{range .items[*]}{@.metadata.name}{\"\n\"}{end}" 2> /dev/null)
         if [ $? -eq 0 ]; then
+            logger "DEBUG" "RESTART_BERFORE_KEYCLOAK_POD=${RESTART_BERFORE_KEYCLOAK_POD}"
             break;
         fi
     done
-    kubectl rollout restart deploy -n exastro-platform-authentication-infra keycloak
+    kubectl rollout restart deploy -n exastro-platform-authentication-infra keycloak &> "${CMD_RESULT}"
     if [ $? -ne 0 ]; then
-        echo "ERROR : rollout restart keycloak"
+        logger "ERROR" "CALL : kubectl rollout restart deploy -n exastro-platform-authentication-infra keycloak${LF}`cat ${CMD_RESULT}`"
+        logger "ERROR" "rollout restart keycloak"
         exit 2
     fi
+    logger "INFO" "CALL : kubectl rollout restart deploy -n exastro-platform-authentication-infra keycloak${LF}`cat ${CMD_RESULT}`"
 
     #
     # wait for restart
     #
     STEP=$(expr ${STEP} + 1)
-    echo "**** STEP : ${STEP} / ${ALLSTEPS} : wait for restart ..."
+    logger "INFO" "**** STEP : ${STEP} / ${ALLSTEPS} : wait for restart ..."
 
     echo -n "waiting ..."
     while true; do
@@ -7453,7 +7499,7 @@ data:
         if [ $? -ne 0 ]; then
             continue
         fi
-        if [ "${RESTART_BERFORE_API_POD}" == "${RESTART_AFTER_API_POD}" ]; then
+        if [ "${RESTART_BERFORE_API_POD}" = "${RESTART_AFTER_API_POD}" ]; then
             continue;
         fi
 
@@ -7461,7 +7507,7 @@ data:
         if [ $? -ne 0 ]; then
             continue
         fi
-        if [ "${RESTART_BERFORE_KEYCLOAK_POD}" == "${RESTART_AFTER_KEYCLOAK_POD}" ]; then
+        if [ "${RESTART_BERFORE_KEYCLOAK_POD}" = "${RESTART_AFTER_KEYCLOAK_POD}" ]; then
             continue;
         fi
 
@@ -7469,11 +7515,14 @@ data:
         break;
     done;
 
+    logger "DEBUG" "RESTART_AFTER_API_POD=${RESTART_AFTER_API_POD}"
+    logger "DEBUG" "RESTART_AFTER_KEYCLOAK_POD=${RESTART_AFTER_KEYCLOAK_POD}"
+
     #
     # Setting api call
     #
     STEP=$(expr ${STEP} + 1)
-    echo "**** STEP : ${STEP} / ${ALLSTEPS} : Setting api call ..."
+    logger "INFO" "**** STEP : ${STEP} / ${ALLSTEPS} : Setting api call ..."
 
     API_RESPONSE="/tmp/${BASENAME}-infra-setting.$$"
 
@@ -7569,25 +7618,25 @@ data:
         }
     EOF
     if [ $? -ne 0 ]; then
-        echo "ERROR : Setting api call"
+        logger "ERROR" "Setting api call"
         exit 2
     fi
 
     API_RESULT=$(cat "${API_RESPONSE}" | jq -r ".result")
     if [ $? -ne 0 ]; then
-        echo "---- API Error Response ----"
-        cat "${API_RESPONSE}"
-        echo "ERROR : Setting api call"
+        logger "ERROR" "Setting api response:\n`cat ${API_RESPONSE}`"
+        logger "ERROR" "Api Logs:\n`kubectl logs deploy/authentication-infra-api -n exastro-platform-authentication-infra`"
+        logger "ERROR" "Setting api"
         exit 2
     fi
     if [ "${API_RESULT}" != "200" ]; then
-        echo "---- API Error Response ----"
-        cat "${API_RESPONSE}"
-        echo "ERROR : Setting api call"
+        logger "ERROR" "Setting api response:\n`cat ${API_RESPONSE}`"
+        logger "ERROR" "Api Logs:\n`kubectl logs deploy/authentication-infra-api -n exastro-platform-authentication-infra`"
+        logger "ERROR" "Setting api"
         exit 2
     fi
 
-    echo "**** ${BASENAME} completed successfully ****"
+    logger "INFO" "**** ${BASENAME} completed successfully ****"
     exit 0
 kind: ConfigMap
 metadata:
@@ -7629,9 +7678,15 @@ spec:
       - name: epoch-setting-tools-script
         configMap:
           name: epoch-setting-tools-script
+      - name: setting-logs
+        hostPath:
+          path: /var/data/epoch/epoch-setting-tools
+          type: DirectoryOrCreate
       containers:
       - name: epoch-setting-tools
         image: exastro/epoch-kube-command:0.1.5_20211026_1600
         volumeMounts:
         - mountPath: /scripts
           name: epoch-setting-tools-script
+        - mountPath: /var/log/epoch
+          name: setting-logs
